on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true
      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          inlineScript: Get-AzResourceGroup -Name "TF-State"
          azPSVersion: "latest"
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with: 
          terraform_version: 1.5.6
      - name: Initialize Terraform
        run: terraform init
      - name: Plan Terraform Changes
        run: terraform plan -out=tfplan -input=false
      - name: Apply Terraform Changes
        run: terraform apply -input=false tfplan
      - name: Clean up
        run: rm -rf .terraform